name: Lint & Test

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install graphviz
        run: sudo apt-get install graphviz graphviz-dev
      - name: Setup Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - run: poetry run pycodestyle
      - run: poetry run black --check .
      - name: pylint
        run: poetry run pylint */
        env:
          DATABASE_URL: sqlite:///testdb.sql
      - run: poetry run coverage run --source='.' manage.py test
        env:
          DJANGO_SETTINGS_MODULE: settings
          DATABASE_URL: sqlite://testdb.sql
      - run: poetry run coverage report
